version: 2.1
jobs:
    build:
        docker:
            - image: circleci/rust
        steps:
            - checkout
            - run: cargo fmt
            - run: sudo apt update
            - run: sudo apt install cmake libleveldb-dev libsqlite3-dev
            - run: cargo test
workflows:
    version: 2
    tests:
        jobs:
            - build
